import React, { createContext, useContext, useState, useEffect } from 'react';

// === DICCIONARIOS DE IDIOMAS ===
const translations = {
  es: {
    // Generales
    'app.name': 'NeuroTek',
    'btn.save': 'Guardar Cambios',
    'btn.cancel': 'Cancelar',
    'btn.edit': 'Editar',
    
    // Configuración
    'config.title': 'Configuración',
    'config.subtitle': 'Personaliza tu experiencia en NeuroTek',
    'config.tab.profile': 'Perfil',
    'config.tab.notifications': 'Notificaciones',
    'config.tab.appearance': 'Apariencia',
    'config.appearance.title': 'Personalización de la Interfaz',
    'config.appearance.subtitle': 'Ajusta la apariencia de la aplicación',
    'config.appearance.theme': 'Tema',
    'config.appearance.theme.light': 'Claro',
    'config.appearance.theme.dark': 'Oscuro',
    'config.appearance.language': 'Idioma',
    'config.appearance.language.es': 'Español',
    'config.appearance.language.en': 'Inglés',
    'config.appearance.currency': 'Formato de Moneda',
    'config.appearance.currency.pen': 'PEN (S/)',
    'config.appearance.currency.usd': 'USD ($)',
    'config.appearance.currency.mxn': 'MXN ($)',

    // Tienda - Inicio
    'home.hero.badge': '100% Calidad Garantizada',
    'home.hero.title': 'El Futuro del Gaming Está Aquí',
    'home.hero.subtitle': 'Equípate con la mejor tecnología. Rendimiento extremo, diseño impecable y potencia sin límites para dominar cada partida.',
    'home.hero.btn.catalog': 'Explorar Catálogo',
    'home.hero.btn.offers': 'Ver Ofertas',
    
    'home.features.shipping.title': 'Envío Gratis',
    'home.features.shipping.desc': 'En pedidos mayores a',
    'home.features.support.title': 'Soporte 24/7',
    'home.features.support.desc': 'Atención técnica especializada',
    'home.features.warranty.title': 'Garantía Total',
    'home.features.warranty.desc': '1 año en todos los productos',
    'home.features.secure.title': 'Pago Seguro',
    'home.features.secure.desc': '100% protegido',

    'home.trending.title': 'Productos en Tendencia',
    'home.trending.subtitle': 'Lo más buscado por los gamers esta semana',
    'home.trending.btn.add': 'Agregar',

    'home.categories.title': 'Categorías Principales',
    'home.categories.subtitle': 'Encuentra exactamente lo que necesitas para tu setup',
    
    'home.cta.title': '¿Listo para armar tu Setup ideal?',
    'home.cta.subtitle': 'Únete a miles de gamers que ya confían en NeuroTek para llevar su rendimiento al máximo nivel.',
    'home.cta.btn': 'Crear Cuenta Gratis',

    // Admin Layout
    'admin.nav.dashboard': 'Dashboard',
    'admin.nav.productos': 'Productos',
    'admin.nav.inventario': 'Inventario',
    'admin.nav.ordenes': 'Órdenes',
    'admin.nav.clientes': 'Clientes',
    'admin.nav.analytics': 'Analytics',
    'admin.nav.reportes': 'Reportes',
    'admin.nav.notificaciones': 'Notificaciones',
    'admin.nav.equipo': 'Equipo',
    'admin.nav.configuracion': 'Configuración',
    'admin.nav.logout': 'Cerrar Sesión',

    // Admin Dashboard
    'admin.dash.welcome': 'Bienvenido de nuevo',
    'admin.dash.subtitle': 'Resumen de tu negocio en tiempo real',
    'admin.dash.sales': 'Ventas Totales',
    'admin.dash.sales.realtime': 'Realtime',
    'admin.dash.products': 'Productos',
    'admin.dash.products.stock': 'En inventario',
    'admin.dash.orders': 'Pedidos',
    'admin.dash.orders.total': 'Totales',
    'admin.dash.clients': 'Clientes',
    'admin.dash.clients.registered': 'Registrados',
    'admin.dash.chart.title': 'Ventas y Ganancias',
    'admin.dash.chart.subtitle': 'Ingresos reales (Margen est. 30%)',
    'admin.dash.pie.title': 'Inventario por Categoría',
    'admin.dash.pie.subtitle': 'Distribución en stock',
    'admin.dash.recent': 'Últimos Pedidos',
    'admin.dash.recent.subtitle': 'Actividad reciente',
    'admin.dash.table.client': 'CLIENTE',
    'admin.dash.table.items': 'ITEMS',
    'admin.dash.table.amount': 'MONTO',
    'admin.dash.table.status': 'ESTADO',
    'admin.dash.status.completada': 'Completada',
    'admin.dash.status.completado': 'Completado',
    'admin.dash.status.pendiente': 'Pendiente',
    'admin.dash.status.cancelada': 'Cancelada',
    'admin.dash.status.enviado': 'Enviado',
    'admin.dash.status.procesando': 'Procesando',
    'admin.dash.no_recent_orders': 'No hay pedidos recientes',
    'admin.dash.recent_activity': 'Actividad Reciente',
    'admin.dash.recent_activity.subtitle': 'Últimas transacciones',
    'admin.dash.no_recent_activity': 'No hay actividad reciente',
    'admin.dash.stock_alerts': 'Alertas de Stock Bajo',
    'admin.dash.stock_alerts.subtitle': 'Productos críticos',
    'admin.dash.no_stock_alerts': 'Inventario saludable, no hay alertas',
    'admin.dash.min_required': 'Mínimo requerido:',
    'admin.dash.units': 'unidades',
    'admin.dash.units_short': 'uni.',
    'admin.dash.activity.sale': 'Venta',

    // Admin Inventario
    'admin.inv.status.out_of_stock': 'Sin Stock',
    'admin.inv.status.critical': 'Crítico',
    'admin.inv.status.low': 'Bajo',
    'admin.inv.status.normal': 'Normal',
    'admin.inv.title': 'Inventario',
    'admin.inv.subtitle': 'Gestión y control de stock',
    'admin.inv.btn_export': 'Exportar',
    'admin.inv.stats.total': 'Items Totales',
    'admin.inv.stats.low': 'Stock Bajo',
    'admin.inv.stats.critical': 'Stock Crítico',
    'admin.inv.table.title': 'Stock de Productos',
    'admin.inv.table.subtitle': 'Monitoreo en tiempo real del inventario',
    'admin.inv.search': 'Buscar por nombre o SKU...',
    'admin.inv.filter.all': 'Todos',
    'admin.inv.filter.btn': 'Filtros',
    'admin.inv.table.col_product': 'Producto',
    'admin.inv.table.col_sku': 'SKU',
    'admin.inv.table.col_stock': 'Stock',
    'admin.inv.table.col_min_stock': 'Min. Stock',
    'admin.inv.table.col_location': 'Ubicación',
    'admin.inv.table.col_status': 'Estado',
    'admin.inv.table.col_action': 'Acción',
    'admin.inv.table.empty': 'No se encontraron productos',
    'admin.inv.btn_adjust': 'Ajustar stock',
    'admin.inv.footer.showing': 'Mostrando',
    'admin.inv.footer.of': 'de',
    'admin.inv.footer.products': 'productos',
    'admin.inv.footer.realtime': 'Tiempo real activo',

    // Admin Ordenes
    'admin.ord.title': 'Órdenes',
    'admin.ord.subtitle': 'Gestión de pedidos y ventas',
    'admin.ord.stats.total': 'Órdenes Totales',
    'admin.ord.stats.sales_today': 'Ventas Hoy',
    'admin.ord.stats.pending': 'Pendientes',
    'admin.ord.table.title': 'Órdenes Recientes',
    'admin.ord.table.subtitle': 'Historial de pedidos y transacciones',
    'admin.ord.search': 'Buscar por cliente o ID...',
    'admin.ord.filter.all_states': 'Todos los estados',
    'admin.ord.table.col_order': 'Orden',
    'admin.ord.table.col_client': 'Cliente',
    'admin.ord.table.col_date': 'Fecha',
    'admin.ord.table.col_items': 'Items',
    'admin.ord.table.col_total': 'Total',
    'admin.ord.table.col_status': 'Estado',
    'admin.ord.table.col_actions': 'Acciones',
    'admin.ord.loading': 'Cargando órdenes...',
    'admin.ord.empty': 'No se encontraron órdenes registradas.',
    'admin.ord.view_detail': 'Ver detalle',
    'admin.ord.footer.showing': 'Mostrando',
    'admin.ord.footer.of': 'de',
    'admin.ord.footer.orders': 'órdenes',
    'admin.ord.modal.title': 'Orden',
    'admin.ord.modal.products': 'Productos',
    'admin.ord.modal.no_details': 'Detalles no disponibles',
    'admin.ord.modal.total': 'Total de la orden',
    'admin.ord.modal.change_status': 'Cambiar estado',
    'admin.ord.modal.close': 'Cerrar',

    // Admin Clientes
    'admin.cli.new_client_default': 'Cliente Nuevo',
    'admin.cli.no_email': 'Sin correo',
    'admin.cli.no_phone': 'Sin teléfono',
    'admin.cli.default_location': 'Lima, Perú',
    'admin.cli.title': 'Clientes',
    'admin.cli.subtitle': 'Gestión de clientes y relaciones',
    'admin.cli.stats.total': 'Total Clientes',
    'admin.cli.stats.new_month': 'Nuevos (mes)',
    'admin.cli.stats.vip': 'Clientes VIP',
    'admin.cli.table.title': 'Base de Clientes',
    'admin.cli.table.subtitle': 'Información detallada de clientes',
    'admin.cli.search': 'Buscar clientes...',
    'admin.cli.table.col_client': 'Cliente',
    'admin.cli.table.col_contact': 'Contacto',
    'admin.cli.table.col_location': 'Ubicación',
    'admin.cli.table.col_orders': 'Órdenes',
    'admin.cli.table.col_total': 'Total Gastado',
    'admin.cli.table.col_rating': 'Rating',
    'admin.cli.loading': 'Cargando clientes...',
    'admin.cli.empty': 'No se encontraron clientes registrados.',
    'admin.cli.view_detail': 'Ver detalle',
    'admin.cli.footer.showing': 'Mostrando',
    'admin.cli.footer.of': 'de',
    'admin.cli.footer.clients': 'clientes',
    'admin.cli.modal.title': 'Perfil del Cliente',
    'admin.cli.modal.orders': 'Órdenes',
    'admin.cli.modal.total_spent': 'Total Gastado',
    'admin.cli.modal.close': 'Cerrar',

    // Admin Notificaciones
    'admin.notif.out_of_stock': 'Sin stock',
    'admin.notif.low_stock': 'Stock bajo',
    'admin.notif.units_left': 'solo quedan',
    'admin.notif.time_now': 'Actual',
    'admin.notif.order_completed': 'Orden completada',
    'admin.notif.new_order': 'Nueva orden',
    'admin.notif.order_made': 'realizó una orden de',
    'admin.notif.new_order_realtime': '¡Nueva orden en tiempo real!',
    'admin.notif.just_now': 'Justo ahora',
    'admin.notif.new_client': 'Nuevo cliente registrado',
    'admin.notif.client_registered': 'se registró en el sistema',
    'admin.notif.loading': 'Cargando notificaciones en vivo...',
    'admin.notif.title': 'Notificaciones',
    'admin.notif.new_plural': 'nuevas',
    'admin.notif.subtitle': 'Centro de notificaciones y alertas en tiempo real',
    'admin.notif.mark_all_read': 'Marcar todas como leídas',
    'admin.notif.clear': 'Limpiar',
    'admin.notif.stats.total': 'Total',
    'admin.notif.stats.unread': 'No leídas',
    'admin.notif.stats.critical': 'Críticas',
    'admin.notif.stats.today': 'Hoy',
    'admin.notif.activity.title': 'Actividad Reciente',
    'admin.notif.activity.subtitle': 'Todas tus notificaciones en vivo',
    'admin.notif.empty.title': 'Bandeja vacía',
    'admin.notif.empty.subtitle': 'No tienes notificaciones en este momento',
    'admin.notif.urgent': 'Urgente',
    'admin.notif.mark_read': 'Marcar como leída',
    'admin.notif.delete': 'Eliminar',

    // Admin Analytics
    'admin.ana.tabs.revenue': 'Ingresos',
    'admin.ana.tabs.products': 'Productos',
    'admin.ana.tabs.categories': 'Categorías',
    'admin.ana.tabs.schedule': 'Por Horario',
    'admin.ana.others': 'Otros',
    'admin.ana.various': 'Varios',
    'admin.ana.pdf.title': 'Analytics NeuroTek',
    'admin.ana.pdf.global_metrics': 'Métricas Globales',
    'admin.ana.pdf.total_sales': 'Ventas Totales: S/',
    'admin.ana.pdf.total_orders': 'Total Pedidos:',
    'admin.ana.pdf.total_clients': 'Total Clientes:',
    'admin.ana.pdf.monthly_sales': 'Ventas mensuales',
    'admin.ana.pdf.sales': ': ventas S/',
    'admin.ana.pdf.orders': ', pedidos',
    'admin.ana.pdf.clients': ', clientes',
    'admin.ana.pdf.top_products': 'Productos más vendidos',
    'admin.ana.pdf.units': 'unidades, S/',
    'admin.ana.pdf.income': 'ingresos',
    'admin.ana.loading': 'Sincronizando métricas en tiempo real...',
    'admin.ana.title': 'Analytics',
    'admin.ana.subtitle': 'Análisis detallado de rendimiento y métricas',
    'admin.ana.generating': 'Generando...',
    'admin.ana.export': 'Exportar Reporte',
    'admin.ana.revenue_evolution': 'Evolución de Ingresos',
    'admin.ana.daily_sales': 'Ventas diarias —',
    'admin.ana.until_day': '(hasta el día',
    'admin.ana.sales': 'Ventas',
    'admin.ana.top_products_revenue': 'Top Productos por Ingresos',
    'admin.ana.revenue': 'Ingresos',
    'admin.ana.top_products_detail': 'Detalle de Productos Top',
    'admin.ana.product': 'Producto',
    'admin.ana.units_col': 'Unidades',
    'admin.ana.category_performance': 'Desempeño por Categoría',
    'admin.ana.sales_currency': 'Ventas (S/)',
    'admin.ana.orders': 'Pedidos',
    'admin.ana.schedule_activity': 'Actividad por Horario',
    'admin.ana.sales_lowercase': 'ventas',
    'admin.ana.frequency': 'Frecuencia',

    // Admin Reportes
    'admin.rep.pdf.title': 'Reporte NeuroTek',
    'admin.rep.pdf.summary': 'Resumen',
    'admin.rep.pdf.total_sales': 'Ventas Totales: S/',
    'admin.rep.pdf.products_sold': 'Productos Vendidos (Items):',
    'admin.rep.pdf.clients_registered': 'Clientes Registrados:',
    'admin.rep.pdf.sales_vs_expenses': 'Ventas vs Gastos (Est)',
    'admin.rep.pdf.sales': ': ventas S/',
    'admin.rep.pdf.expenses': ', gastos S/',
    'admin.rep.pdf.cat_distribution': 'Distribución por Categoría',
    'admin.rep.loading': 'Sincronizando reportes en tiempo real...',
    'admin.rep.title': 'Reportes',
    'admin.rep.subtitle': 'Análisis y reportes detallados en tiempo real',
    'admin.rep.generating': 'Generando...',
    'admin.rep.export': 'Exportar',
    'admin.rep.kpi.total_sales': 'Ventas Totales',
    'admin.rep.kpi.based_orders': '↑ En base a órdenes',
    'admin.rep.kpi.products_sold': 'Productos Vendidos',
    'admin.rep.kpi.total_items': '↑ Total de items',
    'admin.rep.kpi.total_clients': 'Total Clientes',
    'admin.rep.kpi.registered_users': '↑ Usuarios registrados',
    'admin.rep.chart.sales_expenses': 'Ventas vs Gastos Operativos (Est.)',
    'admin.rep.chart.gross_sales': 'Ventas Brutas',
    'admin.rep.chart.est_costs': 'Costos Estimados',
    'admin.rep.chart.growth_trend': 'Tendencia de Crecimiento',
    'admin.rep.chart.sales': 'Ventas',
    'admin.rep.chart.cat_value': 'Valor por Categoría',
    'admin.rep.exec_summary.title': 'Resumen Ejecutivo',
    'admin.rep.exec_summary.desc': 'Este reporte en tiempo real detalla las operaciones de tu negocio, extrayendo datos reales de Supabase. Los márgenes de ganancia e ingresos están tabulados al momento del cierre de cada mes.',
    'admin.rep.exec_summary.best_month': 'Mejor Mes (Estimado)',
    'admin.rep.exec_summary.dom_category': 'Categoría Dominante',

    // Admin Configuracion
    'admin.conf.personal_info.title': 'Información Personal',
    'admin.conf.personal_info.subtitle': 'Actualiza tu información de perfil y foto.',
    'admin.conf.personal_info.edit': 'Editar Datos',
    'admin.conf.personal_info.cancel': 'Cancelar',
    'admin.conf.personal_info.profile_pic': 'Foto de perfil',
    'admin.conf.personal_info.profile_pic_desc_1': 'Sube una foto tuya para que tu equipo pueda reconocerte.',
    'admin.conf.personal_info.profile_pic_desc_2': 'Recomendado: JPG, PNG cuadrados.',
    'admin.conf.personal_info.select_file': 'Seleccionar Archivo',
    'admin.conf.personal_info.first_name': 'Nombre',
    'admin.conf.personal_info.last_name': 'Apellido',
    'admin.conf.personal_info.email': 'Correo Electrónico',
    'admin.conf.personal_info.cannot_change': '(No se puede cambiar)',
    'admin.conf.personal_info.phone': 'Teléfono',
    'admin.conf.personal_info.role': 'Rol (Tu rol actual en el sistema)',
    'admin.conf.personal_info.save': 'Guardar Cambios',
    'admin.conf.notif.title': 'Preferencias de Notificaciones',
    'admin.conf.notif.subtitle': 'Controla cómo y cuándo recibes notificaciones',
    'admin.conf.notif.email_title': 'Notificaciones por Email',
    'admin.conf.notif.email_desc': 'Recibe actualizaciones por correo electrónico',
    'admin.conf.notif.stock_title': 'Alertas de Stock Bajo',
    'admin.conf.notif.stock_desc': 'Notificaciones cuando productos tengan stock bajo',
    'admin.conf.notif.new_clients_title': 'Nuevos Clientes Registrados',
    'admin.conf.notif.new_clients_desc': 'Alerta cuando se registre un nuevo usuario en la tienda',
    'admin.conf.notif.weekly_reports_title': 'Reportes Semanales',
    'admin.conf.notif.weekly_reports_desc': 'Resumen semanal de ventas y estadísticas',
    'admin.conf.notif.system_updates_title': 'Actualizaciones del Sistema',
    'admin.conf.notif.system_updates_desc': 'Notificaciones sobre nuevas funciones',
    'admin.conf.notif.marketing_title': 'Marketing y Promociones',
    'admin.conf.notif.marketing_desc': 'Recibe ofertas y promociones especiales',
    'admin.conf.save_prefs': 'Guardar Preferencias',
    'admin.conf.app_color': 'Color Principal de la Aplicación',
    'admin.conf.compact_mode': 'Modo Compacto',
    'admin.conf.compact_desc': 'Reduce el espaciado de la interfaz',
    'admin.conf.privacy.title': 'Datos y Privacidad',
    'admin.conf.privacy.desc': 'Controla tus datos personales',
    'admin.conf.privacy.download': 'Descargar Mis Datos',
    'admin.conf.privacy.delete': 'Eliminar Cuenta',
    'admin.conf.toast.demo': 'Acción deshabilitada en modo Demo (Solo Lectura).',
    'admin.conf.toast.saving_data': 'Guardando datos...',
    'admin.conf.toast.uploading_photo': 'Subiendo foto...',
    'admin.conf.toast.data_saved': 'Datos guardados con éxito',
    'admin.conf.toast.error_saving': 'Error al guardar: ',
    'admin.conf.toast.saving_prefs': 'Guardando preferencias...',
    'admin.conf.toast.prefs_updated': 'Preferencias actualizadas',
    'admin.conf.toast.passwords_not_match': 'Las contraseñas no coinciden',
    'admin.conf.toast.updating_security': 'Actualizando seguridad...',
    'admin.conf.toast.password_updated': 'Contraseña actualizada',
    'admin.conf.toast.global_prefs_saved': '¡Preferencias globales guardadas!',
    'admin.conf.toast.confirm_delete': '¿Estás seguro de que deseas eliminar tu cuenta? Esta acción no se puede deshacer.',
    'admin.conf.toast.processing_request': 'Procesando solicitud...',

    // Admin Equipo
    'admin.team.title': 'Equipo',
    'admin.team.subtitle': 'Gestión de miembros y permisos',
    'admin.team.add_member': 'Agregar Miembro',
    'admin.team.total_members': 'Total Miembros',
    'admin.team.admins': 'Administradores',
    'admin.team.active': 'Activos',
    'admin.team.table_title': 'Miembros del Equipo',
    'admin.team.table_subtitle': 'Administra roles y permisos de usuarios',
    'admin.team.table.member': 'Miembro',
    'admin.team.table.contact': 'Contacto',
    'admin.team.table.role': 'Rol',
    'admin.team.table.status': 'Estado',
    'admin.team.table.join_date': 'Fecha Ingreso',
    'admin.team.role.admin': 'Admin',
    'admin.team.role.seller': 'Vendedor',
    'admin.team.role.client': 'Cliente',
    'admin.team.status.online': 'En línea',
    'admin.team.status.offline': 'Desconectado',
    'admin.team.invite.title': 'Invitar al Equipo',
    'admin.team.invite.subtitle': 'Se enviará una invitación por correo',
    'admin.team.invite.warning': 'Por seguridad, asegúrate de asignar el rol correcto. El usuario recibirá un enlace para establecer su contraseña a través de Supabase Auth.',
    'admin.team.invite.email': 'Correo Electrónico',
    'admin.team.invite.role': 'Rol de Acceso',
    'admin.team.invite.role_admin': 'Administrador (Control Total)',
    'admin.team.invite.role_seller': 'Vendedor (Solo gestionar ventas)',
    'admin.team.invite.cancel': 'Cancelar',
    'admin.team.invite.send': 'Enviar Invitación',
    'admin.team.toast.sending_invite': 'Enviando invitación...',
    'admin.team.toast.invite_sent': 'Invitación enviada a',
    'admin.team.toast.as': 'como',
    'admin.team.toast.demo': 'Acción deshabilitada en modo Demo (Solo Lectura).',

    // Admin Productos
    'admin.prod.title': 'Productos',
    'admin.prod.subtitle': 'productos registrados',
    'admin.prod.search': 'Buscar por nombre o marca...',
    'admin.prod.btn.new': 'Nuevo producto',
    'admin.prod.badge.offer': 'OFERTA',
    'admin.prod.btn.edit': 'Editar',
    'admin.prod.stock': 'Stock:',
    'admin.prod.all': 'Todas las categorías',
    'admin.prod.modal.title': 'Detalles del Producto',
    'admin.prod.modal.noimage': 'Sin imagen',
    'admin.prod.modal.price': 'Precio',
    'admin.prod.modal.availability': 'Disponibilidad:',
    'admin.prod.modal.stock_units': 'unidades en stock',
    'admin.prod.modal.desc': 'Descripción del Producto',
    'admin.prod.modal.nodesc': 'Sin descripción disponible.',
    'admin.prod.modal.brand': 'Marca',
    'admin.prod.modal.model': 'Modelo',
    'admin.prod.modal.category': 'Categoría',
    'admin.prod.modal.status': 'Estado',
    'admin.prod.modal.active': 'Activo',
    'admin.prod.modal.inactive': 'Inactivo',
    'admin.prod.modal.edit': 'Editar producto',
    'admin.prod.modal.close': 'Cerrar',
    'admin.prod.modal.noreviews': '(Sin reseñas aún)',

    // Admin Productos Form
    'admin.prod.form.edit': 'Editar producto',
    'admin.prod.form.new': 'Nuevo producto',
    'admin.prod.form.image': 'Imagen del producto',
    'admin.prod.form.click_upload': 'Clic para subir imagen',
    'admin.prod.form.name_es': 'Nombre (Español) *',
    'admin.prod.form.name_en': 'Nombre (Inglés)',
    'admin.prod.form.price_regular': 'Precio Regular (PEN)',
    'admin.prod.form.stock_avail': 'Stock Disponible',
    'admin.prod.form.promo': 'Promoción Especial',
    'admin.prod.form.promo_desc': 'Activa para destacar este producto en la sección de ofertas',
    'admin.prod.form.price_offer': 'Precio de Oferta (PEN)',
    'admin.prod.form.desc_es': 'Descripción (Español)',
    'admin.prod.form.desc_en': 'Descripción (Inglés)',
    'admin.prod.form.category': 'Categoría',
    'admin.prod.form.select_category': 'Selecciona una categoría',
    'admin.prod.form.brand': 'Marca',
    'admin.prod.form.model': 'Modelo',
    'admin.prod.form.active': 'Producto activo (visible en tienda)',
    'admin.prod.form.cancel': 'Cancelar',
    'admin.prod.form.saving': 'Guardando...',
    'admin.prod.form.save': 'Guardar cambios',
    'admin.prod.form.add': 'Agregar producto',
    'admin.prod.empty': 'No hay productos',
    'admin.prod.empty_desc': 'Agrega tu primer producto con el botón de arriba',
    'admin.prod.form.placeholder_name_es': 'Ej: Mouse Logitech MX Master 3',
    'admin.prod.form.placeholder_name_en': 'Ej: Logitech MX Master 3 Mouse',
    'admin.prod.form.placeholder_price': 'Ej. 199.99',
    'admin.prod.form.placeholder_desc_es': 'Describe el producto...',
    'admin.prod.form.placeholder_desc_en': 'Describe the product...',
    'admin.prod.form.placeholder_brand': 'Ej: Logitech',
    'admin.prod.form.placeholder_model': 'Ej: MX Master 3'
  },
  en: {
    // Generales
    'app.name': 'NeuroTek',
    'btn.save': 'Save Changes',
    'btn.cancel': 'Cancel',
    'btn.edit': 'Edit',
    
    // Configuración
    'config.title': 'Settings',
    'config.subtitle': 'Customize your NeuroTek experience',
    'config.tab.profile': 'Profile',
    'config.tab.notifications': 'Notifications',
    'config.tab.appearance': 'Appearance',
    'config.appearance.title': 'Interface Customization',
    'config.appearance.subtitle': 'Adjust the application appearance',
    'config.appearance.theme': 'Theme',
    'config.appearance.theme.light': 'Light',
    'config.appearance.theme.dark': 'Dark',
    'config.appearance.language': 'Language',
    'config.appearance.language.es': 'Spanish',
    'config.appearance.language.en': 'English',
    'config.appearance.currency': 'Currency Format',
    'config.appearance.currency.pen': 'PEN (S/)',
    'config.appearance.currency.usd': 'USD ($)',
    'config.appearance.currency.mxn': 'MXN ($)',

    // Tienda - Inicio
    'home.hero.badge': '100% Quality Guaranteed',
    'home.hero.title': 'The Future of Gaming is Here',
    'home.hero.subtitle': 'Equip yourself with the best tech. Extreme performance, flawless design, and limitless power to dominate every match.',
    'home.hero.btn.catalog': 'Explore Catalog',
    'home.hero.btn.offers': 'View Offers',
    
    'home.features.shipping.title': 'Free Shipping',
    'home.features.shipping.desc': 'On orders over',
    'home.features.support.title': '24/7 Support',
    'home.features.support.desc': 'Specialized technical support',
    'home.features.warranty.title': 'Full Warranty',
    'home.features.warranty.desc': '1 year on all products',
    'home.features.secure.title': 'Secure Payment',
    'home.features.secure.desc': '100% protected',

    'home.trending.title': 'Trending Products',
    'home.trending.subtitle': 'Most wanted by gamers this week',
    'home.trending.btn.add': 'Add to Cart',

    'home.categories.title': 'Top Categories',
    'home.categories.subtitle': 'Find exactly what you need for your setup',
    
    'home.cta.title': 'Ready to build your ideal Setup?',
    'home.cta.subtitle': 'Join thousands of gamers who already trust NeuroTek to take their performance to the maximum level.',
    'home.cta.btn': 'Create Free Account',

    // Admin Layout
    'admin.nav.dashboard': 'Dashboard',
    'admin.nav.productos': 'Products',
    'admin.nav.inventario': 'Inventory',
    'admin.nav.ordenes': 'Orders',
    'admin.nav.clientes': 'Customers',
    'admin.nav.analytics': 'Analytics',
    'admin.nav.reportes': 'Reports',
    'admin.nav.notificaciones': 'Notifications',
    'admin.nav.equipo': 'Team',
    'admin.nav.configuracion': 'Settings',
    'admin.nav.logout': 'Sign Out',

    // Admin Dashboard
    'admin.dash.welcome': 'Welcome back',
    'admin.dash.subtitle': 'Real-time overview of your business',
    'admin.dash.sales': 'Total Sales',
    'admin.dash.sales.realtime': 'Realtime',
    'admin.dash.products': 'Products',
    'admin.dash.products.stock': 'In stock',
    'admin.dash.orders': 'Orders',
    'admin.dash.orders.total': 'Total',
    'admin.dash.clients': 'Customers',
    'admin.dash.clients.registered': 'Registered',
    'admin.dash.chart.title': 'Sales and Revenue',
    'admin.dash.chart.subtitle': 'Real income (Est. margin 30%)',
    'admin.dash.pie.title': 'Inventory by Category',
    'admin.dash.pie.subtitle': 'Stock distribution',
    'admin.dash.recent': 'Recent Orders',
    'admin.dash.recent.subtitle': 'Recent activity',
    'admin.dash.table.client': 'CUSTOMER',
    'admin.dash.table.items': 'ITEMS',
    'admin.dash.table.amount': 'AMOUNT',
    'admin.dash.table.status': 'STATUS',
    'admin.dash.status.completada': 'Completed',
    'admin.dash.status.completado': 'Completed',
    'admin.dash.status.pendiente': 'Pending',
    'admin.dash.status.cancelada': 'Cancelled',
    'admin.dash.status.enviado': 'Shipped',
    'admin.dash.status.procesando': 'Processing',
    'admin.dash.no_recent_orders': 'No recent orders',
    'admin.dash.recent_activity': 'Recent Activity',
    'admin.dash.recent_activity.subtitle': 'Latest transactions',
    'admin.dash.no_recent_activity': 'No recent activity',
    'admin.dash.stock_alerts': 'Low Stock Alerts',
    'admin.dash.stock_alerts.subtitle': 'Critical products',
    'admin.dash.no_stock_alerts': 'Healthy inventory, no alerts',
    'admin.dash.min_required': 'Minimum required:',
    'admin.dash.units': 'units',
    'admin.dash.units_short': 'uni.',
    'admin.dash.activity.sale': 'Sale',

    // Admin Inventario
    'admin.inv.status.out_of_stock': 'Out of Stock',
    'admin.inv.status.critical': 'Critical',
    'admin.inv.status.low': 'Low',
    'admin.inv.status.normal': 'Normal',
    'admin.inv.title': 'Inventory',
    'admin.inv.subtitle': 'Stock management and control',
    'admin.inv.btn_export': 'Export',
    'admin.inv.stats.total': 'Total Items',
    'admin.inv.stats.low': 'Low Stock',
    'admin.inv.stats.critical': 'Critical Stock',
    'admin.inv.table.title': 'Product Stock',
    'admin.inv.table.subtitle': 'Real-time inventory monitoring',
    'admin.inv.search': 'Search by name or SKU...',
    'admin.inv.filter.all': 'All',
    'admin.inv.filter.btn': 'Filters',
    'admin.inv.table.col_product': 'Product',
    'admin.inv.table.col_sku': 'SKU',
    'admin.inv.table.col_stock': 'Stock',
    'admin.inv.table.col_min_stock': 'Min. Stock',
    'admin.inv.table.col_location': 'Location',
    'admin.inv.table.col_status': 'Status',
    'admin.inv.table.col_action': 'Action',
    'admin.inv.table.empty': 'No products found',
    'admin.inv.btn_adjust': 'Adjust stock',
    'admin.inv.footer.showing': 'Showing',
    'admin.inv.footer.of': 'of',
    'admin.inv.footer.products': 'products',
    'admin.inv.footer.realtime': 'Real-time active',

    // Admin Ordenes
    'admin.ord.title': 'Orders',
    'admin.ord.subtitle': 'Order and sales management',
    'admin.ord.stats.total': 'Total Orders',
    'admin.ord.stats.sales_today': 'Sales Today',
    'admin.ord.stats.pending': 'Pending',
    'admin.ord.table.title': 'Recent Orders',
    'admin.ord.table.subtitle': 'Order and transaction history',
    'admin.ord.search': 'Search by customer or ID...',
    'admin.ord.filter.all_states': 'All statuses',
    'admin.ord.table.col_order': 'Order',
    'admin.ord.table.col_client': 'Customer',
    'admin.ord.table.col_date': 'Date',
    'admin.ord.table.col_items': 'Items',
    'admin.ord.table.col_total': 'Total',
    'admin.ord.table.col_status': 'Status',
    'admin.ord.table.col_actions': 'Actions',
    'admin.ord.loading': 'Loading orders...',
    'admin.ord.empty': 'No registered orders found.',
    'admin.ord.view_detail': 'View detail',
    'admin.ord.footer.showing': 'Showing',
    'admin.ord.footer.of': 'of',
    'admin.ord.footer.orders': 'orders',
    'admin.ord.modal.title': 'Order',
    'admin.ord.modal.products': 'Products',
    'admin.ord.modal.no_details': 'Details not available',
    'admin.ord.modal.total': 'Order Total',
    'admin.ord.modal.change_status': 'Change status',
    'admin.ord.modal.close': 'Close',

    // Admin Clientes
    'admin.cli.new_client_default': 'New Customer',
    'admin.cli.no_email': 'No email',
    'admin.cli.no_phone': 'No phone',
    'admin.cli.default_location': 'Lima, Peru',
    'admin.cli.title': 'Customers',
    'admin.cli.subtitle': 'Customer and relationship management',
    'admin.cli.stats.total': 'Total Customers',
    'admin.cli.stats.new_month': 'New (month)',
    'admin.cli.stats.vip': 'VIP Customers',
    'admin.cli.table.title': 'Customer Base',
    'admin.cli.table.subtitle': 'Detailed customer information',
    'admin.cli.search': 'Search customers...',
    'admin.cli.table.col_client': 'Customer',
    'admin.cli.table.col_contact': 'Contact',
    'admin.cli.table.col_location': 'Location',
    'admin.cli.table.col_orders': 'Orders',
    'admin.cli.table.col_total': 'Total Spent',
    'admin.cli.table.col_rating': 'Rating',
    'admin.cli.loading': 'Loading customers...',
    'admin.cli.empty': 'No registered customers found.',
    'admin.cli.view_detail': 'View detail',
    'admin.cli.footer.showing': 'Showing',
    'admin.cli.footer.of': 'of',
    'admin.cli.footer.clients': 'customers',
    'admin.cli.modal.title': 'Customer Profile',
    'admin.cli.modal.orders': 'Orders',
    'admin.cli.modal.total_spent': 'Total Spent',
    'admin.cli.modal.close': 'Close',

    // Admin Notificaciones
    'admin.notif.out_of_stock': 'Out of stock',
    'admin.notif.low_stock': 'Low stock',
    'admin.notif.units_left': 'only',
    'admin.notif.time_now': 'Current',
    'admin.notif.order_completed': 'Order completed',
    'admin.notif.new_order': 'New order',
    'admin.notif.order_made': 'made an order of',
    'admin.notif.new_order_realtime': 'New real-time order!',
    'admin.notif.just_now': 'Just now',
    'admin.notif.new_client': 'New customer registered',
    'admin.notif.client_registered': 'registered in the system',
    'admin.notif.loading': 'Loading live notifications...',
    'admin.notif.title': 'Notifications',
    'admin.notif.new_plural': 'new',
    'admin.notif.subtitle': 'Real-time notifications and alerts center',
    'admin.notif.mark_all_read': 'Mark all as read',
    'admin.notif.clear': 'Clear',
    'admin.notif.stats.total': 'Total',
    'admin.notif.stats.unread': 'Unread',
    'admin.notif.stats.critical': 'Critical',
    'admin.notif.stats.today': 'Today',
    'admin.notif.activity.title': 'Recent Activity',
    'admin.notif.activity.subtitle': 'All your live notifications',
    'admin.notif.empty.title': 'Empty inbox',
    'admin.notif.empty.subtitle': 'You have no notifications at this time',
    'admin.notif.urgent': 'Urgent',
    'admin.notif.mark_read': 'Mark as read',
    'admin.notif.delete': 'Delete',

    // Admin Analytics
    'admin.ana.tabs.revenue': 'Revenue',
    'admin.ana.tabs.products': 'Products',
    'admin.ana.tabs.categories': 'Categories',
    'admin.ana.tabs.schedule': 'By Schedule',
    'admin.ana.others': 'Others',
    'admin.ana.various': 'Various',
    'admin.ana.pdf.title': 'NeuroTek Analytics',
    'admin.ana.pdf.global_metrics': 'Global Metrics',
    'admin.ana.pdf.total_sales': 'Total Sales: $',
    'admin.ana.pdf.total_orders': 'Total Orders:',
    'admin.ana.pdf.total_clients': 'Total Customers:',
    'admin.ana.pdf.monthly_sales': 'Monthly sales',
    'admin.ana.pdf.sales': ': sales $',
    'admin.ana.pdf.orders': ', orders',
    'admin.ana.pdf.clients': ', customers',
    'admin.ana.pdf.top_products': 'Top selling products',
    'admin.ana.pdf.units': 'units, $',
    'admin.ana.pdf.income': 'revenue',
    'admin.ana.loading': 'Synchronizing real-time metrics...',
    'admin.ana.title': 'Analytics',
    'admin.ana.subtitle': 'Detailed performance analysis and metrics',
    'admin.ana.generating': 'Generating...',
    'admin.ana.export': 'Export Report',
    'admin.ana.revenue_evolution': 'Revenue Evolution',
    'admin.ana.daily_sales': 'Daily sales —',
    'admin.ana.until_day': '(until day',
    'admin.ana.sales': 'Sales',
    'admin.ana.top_products_revenue': 'Top Products by Revenue',
    'admin.ana.revenue': 'Revenue',
    'admin.ana.top_products_detail': 'Top Products Detail',
    'admin.ana.product': 'Product',
    'admin.ana.units_col': 'Units',
    'admin.ana.category_performance': 'Performance by Category',
    'admin.ana.sales_currency': 'Sales ($)',
    'admin.ana.orders': 'Orders',
    'admin.ana.schedule_activity': 'Activity by Schedule',
    'admin.ana.sales_lowercase': 'sales',
    'admin.ana.frequency': 'Frequency',

    // Admin Reportes
    'admin.rep.pdf.title': 'NeuroTek Report',
    'admin.rep.pdf.summary': 'Summary',
    'admin.rep.pdf.total_sales': 'Total Sales: $',
    'admin.rep.pdf.products_sold': 'Products Sold (Items):',
    'admin.rep.pdf.clients_registered': 'Registered Customers:',
    'admin.rep.pdf.sales_vs_expenses': 'Sales vs Expenses (Est)',
    'admin.rep.pdf.sales': ': sales $',
    'admin.rep.pdf.expenses': ', expenses $',
    'admin.rep.pdf.cat_distribution': 'Distribution by Category',
    'admin.rep.loading': 'Synchronizing real-time reports...',
    'admin.rep.title': 'Reports',
    'admin.rep.subtitle': 'Detailed analysis and reports in real time',
    'admin.rep.generating': 'Generating...',
    'admin.rep.export': 'Export',
    'admin.rep.kpi.total_sales': 'Total Sales',
    'admin.rep.kpi.based_orders': '↑ Based on orders',
    'admin.rep.kpi.products_sold': 'Products Sold',
    'admin.rep.kpi.total_items': '↑ Total items',
    'admin.rep.kpi.total_clients': 'Total Customers',
    'admin.rep.kpi.registered_users': '↑ Registered users',
    'admin.rep.chart.sales_expenses': 'Sales vs Operating Expenses (Est.)',
    'admin.rep.chart.gross_sales': 'Gross Sales',
    'admin.rep.chart.est_costs': 'Estimated Costs',
    'admin.rep.chart.growth_trend': 'Growth Trend',
    'admin.rep.chart.sales': 'Sales',
    'admin.rep.chart.cat_value': 'Value by Category',
    'admin.rep.exec_summary.title': 'Executive Summary',
    'admin.rep.exec_summary.desc': 'This real-time report details your business operations, extracting real data from Supabase. Profit margins and revenue are tabulated at the close of each month.',
    'admin.rep.exec_summary.best_month': 'Best Month (Estimated)',
    'admin.rep.exec_summary.dom_category': 'Dominant Category',

    // Admin Configuracion
    'admin.conf.personal_info.title': 'Personal Information',
    'admin.conf.personal_info.subtitle': 'Update your profile information and photo.',
    'admin.conf.personal_info.edit': 'Edit Data',
    'admin.conf.personal_info.cancel': 'Cancel',
    'admin.conf.personal_info.profile_pic': 'Profile picture',
    'admin.conf.personal_info.profile_pic_desc_1': 'Upload a photo of yourself so your team can recognize you.',
    'admin.conf.personal_info.profile_pic_desc_2': 'Recommended: Square JPG, PNG.',
    'admin.conf.personal_info.select_file': 'Select File',
    'admin.conf.personal_info.first_name': 'First Name',
    'admin.conf.personal_info.last_name': 'Last Name',
    'admin.conf.personal_info.email': 'Email Address',
    'admin.conf.personal_info.cannot_change': '(Cannot be changed)',
    'admin.conf.personal_info.phone': 'Phone Number',
    'admin.conf.personal_info.role': 'Role (Your current role in the system)',
    'admin.conf.personal_info.save': 'Save Changes',
    'admin.conf.notif.title': 'Notification Preferences',
    'admin.conf.notif.subtitle': 'Control how and when you receive notifications',
    'admin.conf.notif.email_title': 'Email Notifications',
    'admin.conf.notif.email_desc': 'Receive updates via email',
    'admin.conf.notif.stock_title': 'Low Stock Alerts',
    'admin.conf.notif.stock_desc': 'Notifications when products have low stock',
    'admin.conf.notif.new_clients_title': 'New Registered Customers',
    'admin.conf.notif.new_clients_desc': 'Alert when a new user registers in the store',
    'admin.conf.notif.weekly_reports_title': 'Weekly Reports',
    'admin.conf.notif.weekly_reports_desc': 'Weekly summary of sales and statistics',
    'admin.conf.notif.system_updates_title': 'System Updates',
    'admin.conf.notif.system_updates_desc': 'Notifications about new features',
    'admin.conf.notif.marketing_title': 'Marketing and Promotions',
    'admin.conf.notif.marketing_desc': 'Receive special offers and promotions',
    'admin.conf.save_prefs': 'Save Preferences',
    'admin.conf.app_color': 'Main App Color',
    'admin.conf.compact_mode': 'Compact Mode',
    'admin.conf.compact_desc': 'Reduces interface spacing',
    'admin.conf.privacy.title': 'Data and Privacy',
    'admin.conf.privacy.desc': 'Control your personal data',
    'admin.conf.privacy.download': 'Download My Data',
    'admin.conf.privacy.delete': 'Delete Account',
    'admin.conf.toast.demo': 'Action disabled in Demo mode (Read Only).',
    'admin.conf.toast.saving_data': 'Saving data...',
    'admin.conf.toast.uploading_photo': 'Uploading photo...',
    'admin.conf.toast.data_saved': 'Data saved successfully',
    'admin.conf.toast.error_saving': 'Error saving: ',
    'admin.conf.toast.saving_prefs': 'Saving preferences...',
    'admin.conf.toast.prefs_updated': 'Preferences updated',
    'admin.conf.toast.passwords_not_match': 'Passwords do not match',
    'admin.conf.toast.updating_security': 'Updating security...',
    'admin.conf.toast.password_updated': 'Password updated',
    'admin.conf.toast.global_prefs_saved': 'Global preferences saved!',
    'admin.conf.toast.confirm_delete': 'Are you sure you want to delete your account? This action cannot be undone.',
    'admin.conf.toast.processing_request': 'Processing request...',

    // Admin Equipo
    'admin.team.title': 'Team',
    'admin.team.subtitle': 'Member and permission management',
    'admin.team.add_member': 'Add Member',
    'admin.team.total_members': 'Total Members',
    'admin.team.admins': 'Administrators',
    'admin.team.active': 'Active',
    'admin.team.table_title': 'Team Members',
    'admin.team.table_subtitle': 'Manage user roles and permissions',
    'admin.team.table.member': 'Member',
    'admin.team.table.contact': 'Contact',
    'admin.team.table.role': 'Role',
    'admin.team.table.status': 'Status',
    'admin.team.table.join_date': 'Join Date',
    'admin.team.role.admin': 'Admin',
    'admin.team.role.seller': 'Seller',
    'admin.team.role.client': 'Customer',
    'admin.team.status.online': 'Online',
    'admin.team.status.offline': 'Offline',
    'admin.team.invite.title': 'Invite to Team',
    'admin.team.invite.subtitle': 'An invitation will be sent by email',
    'admin.team.invite.warning': 'For security, make sure to assign the correct role. The user will receive a link to set their password via Supabase Auth.',
    'admin.team.invite.email': 'Email Address',
    'admin.team.invite.role': 'Access Role',
    'admin.team.invite.role_admin': 'Administrator (Full Control)',
    'admin.team.invite.role_seller': 'Seller (Only manage sales)',
    'admin.team.invite.cancel': 'Cancel',
    'admin.team.invite.send': 'Send Invitation',
    'admin.team.toast.sending_invite': 'Sending invitation...',
    'admin.team.toast.invite_sent': 'Invitation sent to',
    'admin.team.toast.as': 'as',
    'admin.team.toast.demo': 'Action disabled in Demo mode (Read Only).',

    // Admin Productos
    'admin.prod.title': 'Products',
    'admin.prod.subtitle': 'registered products',
    'admin.prod.search': 'Search by name or brand...',
    'admin.prod.btn.new': 'New Product',
    'admin.prod.badge.offer': 'SALE',
    'admin.prod.btn.edit': 'Edit',
    'admin.prod.stock': 'Stock:',
    'admin.prod.all': 'All categories',
    'admin.prod.modal.title': 'Product Details',
    'admin.prod.modal.noimage': 'No image',
    'admin.prod.modal.price': 'Price',
    'admin.prod.modal.availability': 'Availability:',
    'admin.prod.modal.stock_units': 'units in stock',
    'admin.prod.modal.desc': 'Product Description',
    'admin.prod.modal.nodesc': 'No description available.',
    'admin.prod.modal.brand': 'Brand',
    'admin.prod.modal.model': 'Model',
    'admin.prod.modal.category': 'Category',
    'admin.prod.modal.status': 'Status',
    'admin.prod.modal.active': 'Active',
    'admin.prod.modal.inactive': 'Inactive',
    'admin.prod.modal.edit': 'Edit product',
    'admin.prod.modal.close': 'Close',
    'admin.prod.modal.noreviews': '(No reviews yet)',

    // Admin Productos Form
    'admin.prod.form.edit': 'Edit product',
    'admin.prod.form.new': 'New product',
    'admin.prod.form.image': 'Product image',
    'admin.prod.form.click_upload': 'Click to upload image',
    'admin.prod.form.name_es': 'Name (Spanish) *',
    'admin.prod.form.name_en': 'Name (English)',
    'admin.prod.form.price_regular': 'Regular Price (PEN)',
    'admin.prod.form.stock_avail': 'Available Stock',
    'admin.prod.form.promo': 'Special Promotion',
    'admin.prod.form.promo_desc': 'Activate to highlight this product in the offers section',
    'admin.prod.form.price_offer': 'Offer Price (PEN)',
    'admin.prod.form.desc_es': 'Description (Spanish)',
    'admin.prod.form.desc_en': 'Description (English)',
    'admin.prod.form.category': 'Category',
    'admin.prod.form.select_category': 'Select a category',
    'admin.prod.form.brand': 'Brand',
    'admin.prod.form.model': 'Model',
    'admin.prod.form.active': 'Active product (visible in store)',
    'admin.prod.form.cancel': 'Cancel',
    'admin.prod.form.saving': 'Saving...',
    'admin.prod.form.save': 'Save changes',
    'admin.prod.form.add': 'Add product',
    'admin.prod.empty': 'No products found',
    'admin.prod.empty_desc': 'Add your first product using the button above',
    'admin.prod.form.placeholder_name_es': 'Ex: Logitech MX Master 3 Mouse (ES)',
    'admin.prod.form.placeholder_name_en': 'Ex: Logitech MX Master 3 Mouse',
    'admin.prod.form.placeholder_price': 'Ex. 199.99',
    'admin.prod.form.placeholder_desc_es': 'Describe the product (ES)...',
    'admin.prod.form.placeholder_desc_en': 'Describe the product (EN)...',
    'admin.prod.form.placeholder_brand': 'Ex: Logitech',
    'admin.prod.form.placeholder_model': 'Ex: MX Master 3'
  }
};

const ConfigContext = createContext();

export function ConfigProvider({ children }) {
  // Cargar estado de localStorage o usar defaults
  const [language, setLanguage] = useState(() => localStorage.getItem('nt_lang') || 'es');
  const [currency, setCurrency] = useState(() => localStorage.getItem('nt_currency') || 'PEN');

  useEffect(() => {
    localStorage.setItem('nt_lang', language);
    localStorage.setItem('nt_currency', currency);
  }, [language, currency]);

  // Función de Traducción (t)
  const t = (key) => {
    // Si la llave no existe en el idioma actual, hace fallback a español o devuelve la llave
    return translations[language]?.[key] || translations['es']?.[key] || key;
  };

  // Función de Formateo de Moneda Dinámica
  // Asumimos que los precios base en la base de datos están en Soles (PEN)
  const formatPrice = (basePriceInPen) => {
    const price = parseFloat(basePriceInPen) || 0;
    
    switch (currency) {
      case 'USD':
        // 1 PEN = ~0.263 USD (1 USD = 3.8 PEN)
        return `$${(price / 3.8).toFixed(2)}`;
      case 'MXN':
        // 1 PEN = ~4.5 MXN
        return `MXN $${(price * 4.5).toFixed(2)}`;
      case 'PEN':
      default:
        return `S/ ${price.toFixed(2)}`;
    }
  };

  // Función para campos de base de datos
  const getLocalized = (item, field) => {
    if (!item) return '';
    if (language === 'en') {
      const fieldEn = `${field}_en`;
      if (item[fieldEn]) return item[fieldEn];
    }
    return item[field] || '';
  };

  return (
    <ConfigContext.Provider value={{ language, setLanguage, currency, setCurrency, t, formatPrice, getLocalized }}>
      {children}
    </ConfigContext.Provider>
  );
}

export function useConfig() {
  return useContext(ConfigContext);
}
